version: '2'

services:
  bcoin:
    build: .
    ports:
      #-- Mainnet
      #- "8333:8333"
      #- "8332:8332" # RPC
      #-- Testnet
      #- "18333:18333"
      #- "18332:18332" # RPC
      #-- SEGNET4
      - "28901:28901"
      - "28902:28902" # RPC
    environment:
      BCOIN_NETWORK: segnet4 # main, testnet
      BCOIN_PREFIX: /data
    networks:
     - "bcoin"
    volumes:
      - ./docker_data:/data

networks:
  bcoin:
    external:
      # docker network create bcoin
      name: "bcoin"
